### ISSUE TITLE
App stuck on "Listening..." if minimized

### ISSUE THREAD

**Issue by Wruktarr** [flairmax/FlairMax-Issues#8]
Hey there,

I am using FlairMax Beta (v1.1.6.0) from Microsoft Store (Windows 11).
Problem is that if you press "Recognize from audio output" button (do not know if same issue is for "Recognize by microphone" button) and you minimize application, it will be stuck on "Listening..." in right bottom corner until you re-open application and then it finds currently playing song but I wanted to find song then when I minimized FlairMax application (this issue does not occur if you open any other application over FlairMax, so no "minimize" button within control buttons was clicked).

**Comment by ahmed605** [comment]
Hey,

Thanks for reporting the issue. The app currently doesn't support recognizing while minimized because Windows suspends the app when it's minimized so the app isn't really while being minimized, that's the default behavior for UWP apps.

There's a way to fix this, by asking Windows to keep the app alive but this requires usage of "restricted" capabilities which will make app updates to be delayed because Store's update approval/verification process becomes manual (instead of automated) when using restricted capabilities, but I guess it's fine to add this restricted capability because the benefit is worth it?

**Comment by ahmed605** [comment]
I have implemented an option in Settings to keep the app running while minimized as a fix for this, the fix will be available in the upcoming version.
